name: main
on: push
jobs:
  main:
    runs-on: windows-2022
    strategy:
      matrix:
        architecture:
        - x86
        - x64
        compiler:
        - vs2019
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: prepare
      shell: cmd
      run: |
        rem git submodule update --init --recursive
        cd libiconv
        git apply ..\libiconv.patch
        cd ..
    - name: install pscx
      shell: pwsh
      run: install-module pscx -scope CurrentUser -AllowClobber
    - name: build
      shell: pwsh
      run: |
        $x64param = if (${{ matrix.architecture }} -eq 'x64') { $true } else { $false }
        $arm64param = if (${{ matrix.architecture }} -eq 'arm64') { $true } else { $false }
        $vs2008param = if (${{ matrix.compiler }} -eq 'vs2008') { $true } else { $false }
        .\build.ps1 -x64:$x64param -arm64:$arm64param -vs2008:$vs2008param
    - name: debug
      shell: cmd
      run: |
        set PATH=C:\Miniconda3;C:\Miniconda3\Scripts;%PATH%
        python -m pip install mugicli
        pyfind > debug-${{ matrix.architecture }}-{{ matrix.compiler }}.txt
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: debug
        path: debug-${{ matrix.architecture }}-{{ matrix.compiler }}.txt

        