name: main
on: push
jobs:
  main:
    runs-on: windows-2022
    strategy:
      matrix:
        architecture:
        - x86
        - x64
        compiler:
        - vs2019
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: prepare
      shell: cmd
      run: |
        cd libiconv
        git apply ..\libiconv.patch
        cd ..
    - name: build
      shell: pwsh
      run: |
        Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
        install-module pscx -scope CurrentUser -AllowClobber
        $x64param = if ('${{ matrix.architecture }}' -eq 'x64') { $true } else { $false }
        $arm64param = if ('${{ matrix.architecture }}' -eq 'arm64') { $true } else { $false }
        $vs2008param = if ('${{ matrix.compiler }}' -eq 'vs2008') { $true } else { $false }
        pwsh .\build.ps1 -x64:$x64param -arm64:$arm64param -vs2008:$vs2008param
    - name: debug
      shell: cmd
      run: |
        set PATH=C:\Miniconda3;C:\Miniconda3\Scripts;%PATH%
        python -m pip install mugicli
        pyfind > debug-${{ matrix.architecture }}-${{ matrix.compiler }}.txt
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: debug
        path: debug-${{ matrix.architecture }}-${{ matrix.compiler }}.txt
    - name: release
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        allowUpdates: true
        artifacts: dist/*.zip
        token: ${{ secrets.GITHUB_TOKEN }}